### ISSUE TITLE
Каждое следующее слово - с большой буквы amountBonus...

### ISSUE THREAD

**Issue by coursar** [HelgaJava/gitHomeWork2#2]
https://github.com/HelgaJava/gitHomeWork2/blob/965ff20241c2644e76f7625f26a046ce60b7c488/src/Main.java#L6-L8

**Comment by HelgaJava** [comment]
сделано

**Comment by coursar** [comment]
Если сделано - закрывайте, не нужно переоткрывать

**Comment by coursar** [comment]
А ещё лучше - закрывать сообщением коммита

**Comment by HelgaJava** [comment]
а если не переоткрывать, как я пойму, что вы закрыли окончательно мою задачу?

**Comment by coursar** [comment]
Я получу уведомление, что вы закрыли, посмотрю и если меня не устроит, то переоткрою.

Окончательно - отметка о сдаче появится в эксельке.
